#python ~/Pytorch-UNet/LargeImagePredictor.py 38-T-back-corridor-1
#python ~/Pytorch-UNet/LargeImagePredictor.py 38-T-back-corridor-2
#python ~/Pytorch-UNet/LargeImagePredictor.py 38-T-back-corridor-3
#python ~/Pytorch-UNet/LargeImagePredictor.py 38-T-back-corridor-4
#python ~/Pytorch-UNet/LargeImagePredictor.py 38-T-corbel-2
#python ~/Pytorch-UNet/LargeImagePredictor.py 38-T-corbel-4
python ~/Pytorch-UNet/LargeImagePredictor.py 38-T-rightwall-1
python ~/Pytorch-UNet/LargeImagePredictor.py 38-T-rightwall-2
python ~/Pytorch-UNet/LargeImagePredictor.py 38-T-rightwall-3
python ~/Pytorch-UNet/LargeImagePredictor.py 38-T-rightwall-4
